// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdssugngoavqfycfsjjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkc3N1Z25nb2F2cWZ5Y2ZzampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDc2ODksImV4cCI6MjA2MDYyMzY4OX0._Oj8XSSrleEUZl_2Q6zu0DQOFOVSV0pe9Et1qbLTn2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);